# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NuHhe2vQRy6lgNttFLHQYoybUvY71u7a
"""

import requests
import gradio as gr

# Define API call function
def ask_question(question, context):
    url = "https://070c-35-201-151-186.ngrok-free.app/ask"  # Replace with your API URL
    payload = {"question": question, "context": context}
    headers = {"Content-Type": "application/json"}
    response = requests.post(url, json=payload, headers=headers)
    if response.status_code == 200:
        return response.json().get("answer", "No answer found.")
    else:
        return f"Error: {response.status_code} - {response.json()}"

# Build Gradio Interface
iface = gr.Interface(
    fn=ask_question,
    inputs=[
        gr.Textbox(label="Question"),
    ],
    outputs="text",
    title="Medical Question-Answering System",
)

# Launch Gradio Interface
iface.launch()